# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml* ./
RUN npm install --ignore-scripts

# Copy all files
COPY . .

# Build TypeScript
RUN npm run build

# Ensure prompts directory exists
RUN mkdir -p prompts

ENV NODE_ENV=production

CMD ["node", "build/index.js"]
